# Generated by Django 3.0.8 on 2020-09-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likeCount',
        ),
        migrations.AddField(
            model_name='post',
            name='userstamp',
            field=models.CharField(default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
