# Generated by Django 3.0.8 on 2020-09-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200914_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.IntegerField(default=0)),
                ('userstamp', models.CharField(default='none', max_length=32)),
            ],
        ),
    ]
