# Generated by Django 3.0.8 on 2020-07-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200727_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='prodid',
            field=models.IntegerField(default=0),
        ),
    ]
