# Generated by Django 3.0.8 on 2020-08-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200729_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='prodid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='win',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='comment',
            name='prodid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
