# Generated by Django 3.0.8 on 2020-08-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200801_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
