# Generated by Django 3.0.8 on 2020-12-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsConnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userstamp', models.CharField(max_length=32)),
                ('image', models.CharField(max_length=200, null=True)),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('about', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=64)),
                ('grades', models.CharField(max_length=64)),
                ('availability', models.CharField(max_length=200)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
