# Generated by Django 3.0.8 on 2020-12-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsConnect', '0002_subject_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=64)),
                ('grade', models.CharField(default='None', max_length=32)),
                ('availability', models.CharField(max_length=200)),
                ('status', models.CharField(default='Requested', max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('requestor', models.CharField(max_length=32)),
                ('req_email', models.CharField(default='None', max_length=64)),
                ('tutorname', models.CharField(default='None', max_length=32)),
                ('tutoremail', models.CharField(default='None', max_length=64)),
                ('userstamp', models.CharField(default='None', max_length=32)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorid', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=64)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
