# Generated by Django 3.0.8 on 2020-12-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsConnect', '0003_request_tutorsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='status',
            field=models.CharField(default='Requested', max_length=32),
        ),
    ]
