# Generated by Django 3.0.8 on 2020-12-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsConnect', '0005_auto_20201227_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.CharField(max_length=100),
        ),
    ]
